from __future__ import annotations

from smart_proxy.db_postgres import PostgresDatabase

POSTGRES_MIGRATIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "0001_initial_schema",
        (
            """
            CREATE TABLE IF NOT EXISTS credentials (
                id                  TEXT PRIMARY KEY,
                key_value_encrypted BYTEA   NOT NULL,
                key_hash            TEXT    NOT NULL UNIQUE,
                service             TEXT    NOT NULL,
                hostname            TEXT    NOT NULL DEFAULT '',
                source              TEXT,
                found_at            TEXT,
                status              TEXT    NOT NULL DEFAULT 'pending',
                low_balance         INTEGER NOT NULL DEFAULT 0,
                available_models    TEXT    NOT NULL DEFAULT '[]',
                created_at          TEXT    NOT NULL,
                updated_at          TEXT    NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS key_model_status (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                credential_id   TEXT    NOT NULL REFERENCES credentials(id) ON DELETE CASCADE,
                model           TEXT    NOT NULL,
                is_active       INTEGER NOT NULL DEFAULT 0,
                last_checked_at TEXT,
                UNIQUE(credential_id, model)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_credentials_status ON credentials(status)",
            "CREATE INDEX IF NOT EXISTS idx_credentials_key_hash ON credentials(key_hash)",
            "CREATE INDEX IF NOT EXISTS idx_kms_active ON key_model_status(is_active)",
            """
            CREATE TABLE IF NOT EXISTS proxy_api_keys (
                key        TEXT PRIMARY KEY,
                name       TEXT    NOT NULL,
                active     INTEGER NOT NULL DEFAULT 1,
                created_at TEXT    NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS usage_daily (
                date                     TEXT    NOT NULL,
                proxy_key                TEXT    NOT NULL DEFAULT '',
                group_name               TEXT,
                credential_id            TEXT    NOT NULL,
                provider                 TEXT    NOT NULL,
                model                    TEXT    NOT NULL,
                input_tokens             INTEGER NOT NULL DEFAULT 0,
                output_tokens            INTEGER NOT NULL DEFAULT 0,
                cache_read_tokens        INTEGER NOT NULL DEFAULT 0,
                cache_creation_tokens    INTEGER NOT NULL DEFAULT 0,
                cache_creation_5m_tokens INTEGER NOT NULL DEFAULT 0,
                cache_creation_1h_tokens INTEGER NOT NULL DEFAULT 0,
                web_search_requests      INTEGER NOT NULL DEFAULT 0,
                requests                 INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (date, proxy_key, credential_id, provider, model)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_usage_daily_date ON usage_daily(date)",
            """
            CREATE TABLE IF NOT EXISTS model_prices (
                model_prefix         TEXT PRIMARY KEY,
                provider             TEXT NOT NULL,
                input_price          DOUBLE PRECISION NOT NULL,
                output_price         DOUBLE PRECISION NOT NULL,
                cache_read_price     DOUBLE PRECISION,
                cache_write_5m_price DOUBLE PRECISION,
                cache_write_1h_price DOUBLE PRECISION,
                updated_at           TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS anthropic_keys (
                id                TEXT PRIMARY KEY,
                key_type          TEXT    NOT NULL,
                status            TEXT    NOT NULL DEFAULT 'active',
                api_key           TEXT,
                access_token      TEXT,
                refresh_token     TEXT,
                client_id         TEXT    DEFAULT '9d1c250a-e61b-44d9-88ed-5944d1962f5e',
                expires_at        BIGINT,
                scopes            TEXT    DEFAULT '[]',
                subscription_type TEXT    DEFAULT '',
                rate_limit_tier   TEXT    DEFAULT '',
                name              TEXT    NOT NULL DEFAULT '',
                created_at        TEXT    NOT NULL,
                updated_at        TEXT    NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS anthropic_key_snapshots (
                id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id             TEXT    NOT NULL,
                snapshot_kind      TEXT    NOT NULL,
                trigger_event_type TEXT    NOT NULL DEFAULT '',
                status             TEXT    NOT NULL DEFAULT '',
                key_type           TEXT    NOT NULL DEFAULT '',
                name               TEXT    NOT NULL DEFAULT '',
                client_id          TEXT    NOT NULL DEFAULT '',
                expires_at         BIGINT,
                access_token       TEXT,
                refresh_token      TEXT,
                scopes             TEXT    DEFAULT '[]',
                subscription_type  TEXT    DEFAULT '',
                rate_limit_tier    TEXT    DEFAULT '',
                row_json           TEXT    NOT NULL DEFAULT '{}',
                created_at         TEXT    NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_aks_key_created ON anthropic_key_snapshots(key_id, created_at)",
            """
            CREATE TABLE IF NOT EXISTS anthropic_key_events (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                op_id         TEXT    NOT NULL DEFAULT '',
                key_id        TEXT    NOT NULL,
                source        TEXT    NOT NULL DEFAULT '',
                event_type    TEXT    NOT NULL,
                decision      TEXT    NOT NULL DEFAULT '',
                path          TEXT    NOT NULL DEFAULT '',
                model         TEXT,
                http_status   INTEGER,
                request_id    TEXT    NOT NULL DEFAULT '',
                error_type    TEXT    NOT NULL DEFAULT '',
                error_message TEXT    NOT NULL DEFAULT '',
                retry_after   INTEGER,
                snapshot_id   INTEGER,
                context_json  TEXT    NOT NULL DEFAULT '{}',
                created_at    TEXT    NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_ake_key_created ON anthropic_key_events(key_id, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_ake_op_id ON anthropic_key_events(op_id)",
            """
            CREATE TABLE IF NOT EXISTS rate_limit_log (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                provider        TEXT    NOT NULL,
                credential_id   TEXT    NOT NULL,
                started_at      TEXT    NOT NULL,
                retry_after     INTEGER,
                reset_at        TEXT,
                limit_type      TEXT    DEFAULT '',
                utilization_5h  DOUBLE PRECISION,
                utilization_7d  DOUBLE PRECISION,
                requests_during INTEGER NOT NULL DEFAULT 1
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_rll_provider_date ON rate_limit_log(provider, started_at)",
        ),
    ),
    (
        "0002_credentials_key_value_text",
        (
            """
            ALTER TABLE credentials
            RENAME COLUMN key_value_encrypted TO key_value
            """,
            """
            ALTER TABLE credentials
            ALTER COLUMN key_value TYPE TEXT
            USING convert_from(key_value, 'UTF8')
            """,
        ),
    ),
    (
        "0003_anthropic_audit_tables",
        (
            """
            CREATE TABLE IF NOT EXISTS anthropic_key_snapshots (
                id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id             TEXT    NOT NULL,
                snapshot_kind      TEXT    NOT NULL,
                trigger_event_type TEXT    NOT NULL DEFAULT '',
                status             TEXT    NOT NULL DEFAULT '',
                key_type           TEXT    NOT NULL DEFAULT '',
                name               TEXT    NOT NULL DEFAULT '',
                client_id          TEXT    NOT NULL DEFAULT '',
                expires_at         BIGINT,
                access_token       TEXT,
                refresh_token      TEXT,
                scopes             TEXT    DEFAULT '[]',
                subscription_type  TEXT    DEFAULT '',
                rate_limit_tier    TEXT    DEFAULT '',
                row_json           TEXT    NOT NULL DEFAULT '{}',
                created_at         TEXT    NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_aks_key_created ON anthropic_key_snapshots(key_id, created_at)",
            """
            CREATE TABLE IF NOT EXISTS anthropic_key_events (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                op_id         TEXT    NOT NULL DEFAULT '',
                key_id        TEXT    NOT NULL,
                source        TEXT    NOT NULL DEFAULT '',
                event_type    TEXT    NOT NULL,
                decision      TEXT    NOT NULL DEFAULT '',
                path          TEXT    NOT NULL DEFAULT '',
                model         TEXT,
                http_status   INTEGER,
                request_id    TEXT    NOT NULL DEFAULT '',
                error_type    TEXT    NOT NULL DEFAULT '',
                error_message TEXT    NOT NULL DEFAULT '',
                retry_after   INTEGER,
                snapshot_id   INTEGER,
                context_json  TEXT    NOT NULL DEFAULT '{}',
                created_at    TEXT    NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_ake_key_created ON anthropic_key_events(key_id, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_ake_op_id ON anthropic_key_events(op_id)",
        ),
    ),
    (
        "0002_oauth_window_log",
        (
            """
            CREATE TABLE IF NOT EXISTS oauth_window_log (
                id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id             TEXT    NOT NULL,
                window_kind        TEXT    NOT NULL,
                resets_at          TEXT    NOT NULL,
                resets_at_raw      TEXT    NOT NULL,
                first_seen_at      TEXT    NOT NULL,
                first_active_at    TEXT,
                last_seen_at       TEXT    NOT NULL,
                observations       INTEGER NOT NULL DEFAULT 1,
                last_utilization   REAL,
                max_utilization    REAL,
                max_utilization_at TEXT
            )
            """,
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_owl_identity
                ON oauth_window_log(key_id, window_kind, resets_at)
            """,
        ),
    ),
    (
        "0003_oauth_window_drop_log",
        (
            """
            CREATE TABLE IF NOT EXISTS oauth_window_drop_log (
                id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id           TEXT NOT NULL,
                window_kind      TEXT NOT NULL,
                resets_at        TEXT NOT NULL,
                dropped_at       TEXT NOT NULL,
                prev_seen_at     TEXT NOT NULL,
                from_utilization REAL NOT NULL,
                to_utilization   REAL NOT NULL
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_owdl_key
                ON oauth_window_drop_log(key_id, window_kind, dropped_at)
            """,
        ),
    ),
    (
        # Track which usage rows came through the OpenAI-compat transformer.
        # New PK member so compat and native rows for the same key/model/day
        # stay distinct instead of merging.
        "0004_usage_via_openai_compat",
        (
            "ALTER TABLE usage_daily "
            "ADD COLUMN IF NOT EXISTS via_openai_compat INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE usage_daily DROP CONSTRAINT IF EXISTS usage_daily_pkey",
            "ALTER TABLE usage_daily ADD PRIMARY KEY "
            "(date, proxy_key, credential_id, provider, model, via_openai_compat)",
        ),
    ),
    (
        # Per-window token accounting: counters per observed window instance
        # plus a pending bucket for tokens arriving between a window's expiry
        # and the next poll that observes its successor.
        "0005_oauth_window_usage",
        (
            """
            CREATE TABLE IF NOT EXISTS oauth_window_usage (
                window_id                BIGINT NOT NULL,
                model                    TEXT   NOT NULL,
                input_tokens             BIGINT NOT NULL DEFAULT 0,
                output_tokens            BIGINT NOT NULL DEFAULT 0,
                cache_read_tokens        BIGINT NOT NULL DEFAULT 0,
                cache_creation_tokens    BIGINT NOT NULL DEFAULT 0,
                cache_creation_5m_tokens BIGINT NOT NULL DEFAULT 0,
                cache_creation_1h_tokens BIGINT NOT NULL DEFAULT 0,
                web_search_requests      BIGINT NOT NULL DEFAULT 0,
                requests                 BIGINT NOT NULL DEFAULT 0,
                PRIMARY KEY (window_id, model)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS oauth_window_usage_pending (
                key_id                   TEXT   NOT NULL,
                window_kind              TEXT   NOT NULL,
                model                    TEXT   NOT NULL,
                input_tokens             BIGINT NOT NULL DEFAULT 0,
                output_tokens            BIGINT NOT NULL DEFAULT 0,
                cache_read_tokens        BIGINT NOT NULL DEFAULT 0,
                cache_creation_tokens    BIGINT NOT NULL DEFAULT 0,
                cache_creation_5m_tokens BIGINT NOT NULL DEFAULT 0,
                cache_creation_1h_tokens BIGINT NOT NULL DEFAULT 0,
                web_search_requests      BIGINT NOT NULL DEFAULT 0,
                requests                 BIGINT NOT NULL DEFAULT 0,
                updated_at               TEXT   NOT NULL,
                PRIMARY KEY (key_id, window_kind, model)
            )
            """,
        ),
    ),
    (
        # Decommissioned OpenAI/Gemini key subsystem: drop its tables.
        # key_model_status references credentials, so drop it first.
        "0006_drop_openai_credentials",
        (
            "DROP TABLE IF EXISTS key_model_status",
            "DROP TABLE IF EXISTS credentials",
        ),
    ),
    (
        # Additive per-request-kind and per-session usage aggregates
        # (mirrors the usage_kind_daily / usage_session tables added to
        # SCHEMA_SQL / MIGRATIONS for sqlite). usage_daily is untouched.
        "0007_usage_kind_session",
        (
            """
            CREATE TABLE IF NOT EXISTS usage_kind_daily (
                date         TEXT    NOT NULL,
                proxy_key    TEXT    NOT NULL DEFAULT '',
                request_kind TEXT    NOT NULL DEFAULT 'unknown',
                provider     TEXT    NOT NULL,
                model        TEXT    NOT NULL,
                input_tokens             INTEGER NOT NULL DEFAULT 0,
                output_tokens            INTEGER NOT NULL DEFAULT 0,
                cache_read_tokens        INTEGER NOT NULL DEFAULT 0,
                cache_creation_tokens    INTEGER NOT NULL DEFAULT 0,
                cache_creation_5m_tokens INTEGER NOT NULL DEFAULT 0,
                cache_creation_1h_tokens INTEGER NOT NULL DEFAULT 0,
                web_search_requests      INTEGER NOT NULL DEFAULT 0,
                requests                 INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (date, proxy_key, request_kind, provider, model)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_usage_kind_daily_date ON usage_kind_daily(date)",
            """
            CREATE TABLE IF NOT EXISTS usage_session (
                session_id   TEXT    NOT NULL,
                proxy_key    TEXT    NOT NULL DEFAULT '',
                provider     TEXT    NOT NULL,
                model        TEXT    NOT NULL,
                first_date   TEXT    NOT NULL,
                last_date    TEXT    NOT NULL,
                input_tokens             INTEGER NOT NULL DEFAULT 0,
                output_tokens            INTEGER NOT NULL DEFAULT 0,
                cache_read_tokens        INTEGER NOT NULL DEFAULT 0,
                cache_creation_tokens    INTEGER NOT NULL DEFAULT 0,
                cache_creation_5m_tokens INTEGER NOT NULL DEFAULT 0,
                cache_creation_1h_tokens INTEGER NOT NULL DEFAULT 0,
                web_search_requests      INTEGER NOT NULL DEFAULT 0,
                requests                 INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (session_id, proxy_key, provider, model)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_usage_session_key ON usage_session(proxy_key)",
        ),
    ),
    (
        # usage_session gains request_kind (new PK member) + project/title.
        # Existing rows keep request_kind='unknown'; the constant PK member
        # can't collide (new key is a superset of the old unique key).
        "0008_usage_session_kind_title",
        (
            "ALTER TABLE usage_session ADD COLUMN IF NOT EXISTS request_kind TEXT NOT NULL DEFAULT 'unknown'",
            "ALTER TABLE usage_session ADD COLUMN IF NOT EXISTS project TEXT NOT NULL DEFAULT ''",
            "ALTER TABLE usage_session ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT ''",
            "ALTER TABLE usage_session DROP CONSTRAINT IF EXISTS usage_session_pkey",
            "ALTER TABLE usage_session ADD PRIMARY KEY (session_id, proxy_key, request_kind, provider, model)",
        ),
    ),
    (
        "0009_anthropic_keys_role",
        (
            "ALTER TABLE anthropic_keys ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'primary'",
        ),
    ),
    (
        "0010_proxy_key_limits",
        (
            """
            CREATE TABLE IF NOT EXISTS proxy_key_limits (
                proxy_key  TEXT NOT NULL,
                kind       TEXT NOT NULL,
                amount     DOUBLE PRECISION NOT NULL,
                updated_at TEXT NOT NULL,
                PRIMARY KEY (proxy_key, kind)
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS usage_key_hourly (
                hour_utc                 TEXT    NOT NULL,
                proxy_key                TEXT    NOT NULL,
                model                    TEXT    NOT NULL,
                input_tokens             INTEGER NOT NULL DEFAULT 0,
                output_tokens            INTEGER NOT NULL DEFAULT 0,
                cache_read_tokens        INTEGER NOT NULL DEFAULT 0,
                cache_creation_tokens    INTEGER NOT NULL DEFAULT 0,
                cache_creation_5m_tokens INTEGER NOT NULL DEFAULT 0,
                cache_creation_1h_tokens INTEGER NOT NULL DEFAULT 0,
                web_search_requests      INTEGER NOT NULL DEFAULT 0,
                requests                 INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (hour_utc, proxy_key, model)
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_usage_key_hourly_hour ON usage_key_hourly(hour_utc)",
        ),
    ),
    (
        "0011_anthropic_keys_allowed_proxy_keys",
        (
            "ALTER TABLE anthropic_keys ADD COLUMN IF NOT EXISTS "
            "allowed_proxy_keys TEXT NOT NULL DEFAULT '[]'",
        ),
    ),
    (
        # Token counters were created as Postgres INTEGER (int4, max
        # 2_147_483_647). sqlite's INTEGER is 64-bit, so every sqlite-backed
        # test passed while a single long-lived Claude Code session walked
        # usage_session.cache_read_tokens to the int4 ceiling in production --
        # after which its ON CONFLICT sum raised NumericValueOutOfRange on
        # every flush (taking usage_key_hourly, and so the spend limiter's
        # re-seed source, down with it) and query_top_sessions' four-counter
        # ranking sum 500'd GET /api/sessions. Cache-read tokens accrue far
        # faster than any other counter: a busy day already clears 1.1e9 in a
        # single usage_daily row, so the daily tables have limited headroom
        # too. Widen every counter in all four usage tables.
        #
        # One ALTER per table (not per column) so each table is rewritten once.
        # These take ACCESS EXCLUSIVE locks: stop the proxy before migrating.
        # oauth_window_usage/_pending were already BIGINT.
        "0012_usage_counters_bigint",
        tuple(
            "ALTER TABLE {} {}".format(
                table,
                ", ".join(
                    f"ALTER COLUMN {column} TYPE BIGINT"
                    for column in (
                        "input_tokens",
                        "output_tokens",
                        "cache_read_tokens",
                        "cache_creation_tokens",
                        "cache_creation_5m_tokens",
                        "cache_creation_1h_tokens",
                        "web_search_requests",
                        "requests",
                    )
                ),
            )
            for table in (
                "usage_daily",
                "usage_kind_daily",
                "usage_session",
                "usage_key_hourly",
            )
        ),
    ),
    (
        # Forensics for the undeclared weekly-counter wipe: the raw payload
        # (content-deduplicated) plus the wipe events derived from it.
        # TEXT, not JSONB — the snapshot export path is row_json-based.
        "0013_oauth_limit_wipe_forensics",
        (
            """
            CREATE TABLE IF NOT EXISTS oauth_usage_snapshot (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id        TEXT    NOT NULL,
                payload_hash  TEXT    NOT NULL,
                payload_json  TEXT    NOT NULL,
                headers_json  TEXT    NOT NULL,
                first_seen_at TEXT    NOT NULL,
                last_seen_at  TEXT    NOT NULL,
                seen_count    INTEGER NOT NULL DEFAULT 1
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_ous_key_seen
                ON oauth_usage_snapshot(key_id, first_seen_at)
            """,
            """
            CREATE TABLE IF NOT EXISTS oauth_limit_wipe (
                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_id                  TEXT    NOT NULL,
                window_kind             TEXT    NOT NULL,
                observed_at             TEXT    NOT NULL,
                prev_seen_at            TEXT    NOT NULL,
                from_utilization        DOUBLE PRECISION NOT NULL,
                resets_at_claimed       TEXT    NOT NULL,
                hours_before_claimed    DOUBLE PRECISION,
                five_hour_rolled        INTEGER NOT NULL DEFAULT 0,
                five_hour_early_minutes DOUBLE PRECISION,
                source                  TEXT    NOT NULL DEFAULT 'poll',
                context_json            TEXT,
                snapshot_id             BIGINT,
                prev_snapshot_id        BIGINT
            )
            """,
            """
            CREATE INDEX IF NOT EXISTS idx_olw_key
                ON oauth_limit_wipe(key_id, observed_at)
            """,
        ),
    ),
)


async def run_postgres_migrations(database_url: str) -> list[str]:
    db = PostgresDatabase(database_url)
    await db.connect()
    try:
        await db.ensure_migration_table()
        applied = await db.get_applied_migrations()
        newly_applied: list[str] = []
        for name, statements in POSTGRES_MIGRATIONS:
            if name in applied:
                continue
            await db.apply_migration(name, statements)
            newly_applied.append(name)
        await db._seed_model_prices()
        return newly_applied
    finally:
        await db.close()
